### ISSUE TITLE
Upload Speed TEST Possible?

### ISSUE THREAD

**Issue by mehargags** [K4Y5/ServerBench#1]
Hi K4Y5,
I was thinking if there is a possibility of including an UPLOAD test to various locations (as possible) since for a Webserver it is more important to have a sustained upload bandwidth.

Thanks anyways for the comprehensive script.

**Comment by K4Y5** [comment]
Hi,

This script was a result of time that I spent staring at my workstation on a day that I didn't have any real work to do, but still had enough spare time and inclination to track the download links down from looking glass of various providers, sort them geographically and add them into a script.

So, no promises, but I'll see what I can do to create a basic upload speed for at-least a few locations per continent, whenever I feel inclined to do something along those lines.

Sure, no problem. I enjoyed working on this thing, and am glad you found it useful.
