### ISSUE TITLE
Tele2, Canada, CA

### ISSUE THREAD

**Issue by romanrm** [K4Y5/ServerBench#2]
```
    speed_test 'http://speedtest.tele2.net/100MB.zip' 'Tele2, Canada, CA'
```

That's not in Canada, it resolves to:

```
speedtest.tele2.net has address 90.130.70.73
speedtest.tele2.net has IPv6 address 2a00:800:1010::1
```

which appear to be in Stockholm, SE, or very close.

**Comment by K4Y5** [comment]
My bad. That address is anycasted.
I'll shortly remove that test link from the updated version of the script.

Thanks for pointing this out!
